### PR TITLE
Adds constructor without activity requirement

### PR DESCRIPTION
**Pull request by ryanwr**
This should address issue #48 and also partially #50. The new constructor method signature is

`public ParticleSystem(ViewGroup parentView, Drawable drawable, int maxParticles, long timeToLive)`

I've also added a utility method for updating the emitter position but using a view and gravity instead of just the existing method with x and y coords.

### CODE REVIEW

**Comment by plattysoft** [comment]
Thanks for contributing (again)!

To avoid duplicated code, It would be better to have a common constructor with the base implementation that receives a displayMetrics so all the common code is in a single place.

Can you please update it to be like that? 

Otherwise I can merge it and do that refactoring later on myself.

**Comment by ryanwr** [comment]
Ah yes, I'll refactor a bit more to remove some of the duplicated code

**Comment by ryanwr** [comment]
See what you think, there's less duplicated code and one main private constructor which all constructors call.

I've also slightly altered the new constructors parameters to 
`public ParticleSystem(ViewGroup parentView, int maxParticles, Drawable drawable, long timeToLive)`
as it's more inline with the current constructors having maxParticles before drawable.

**Comment by plattysoft** [comment]
thanks for your contribution!

**Pull request merged**
